name: CI/build and test

on:
  push:
    branches: ["main", "dev"]
    paths: ["**.py", "requirements.txt"]
  pull_request:
    branches: ["main", "dev"]
    paths: ["**.py", "requirements.txt"]
  workflow_dispatch:
  workflow_call:

jobs:
  build-fasttree:
    uses: ./.github/workflows/build_fasttree.yml

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      OS: Linux
    needs: build-fasttree
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - run: git fetch --tags

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          python -m pip install pytest

      - name: Install package
        run: pip install .

      - name: Cache FastTree
        uses: actions/cache/restore@v4
        with:
          path: ~/.local/bin/fasttree
          key: ${{ runner.os }}-FastTree

      - name: Test with pytest
        run: |
          pytest -vv
