name: Update files with commit

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false
      
      - name: Fetch tags
        run: git fetch --tags

      - name: Get repo name
        id: repo
        run: |
          repo_name=$(basename "$GITHUB_REPOSITORY")
          echo "repo_name=$repo_name" >> "$GITHUB_OUTPUT"

      - name: Capture version from the latest tag
        id: tag
        run: echo "version=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> "$GITHUB_OUTPUT"

      - name: Check version in README.md
        id: readme
        run: |
          cap=$(grep -oP "${{ steps.repo.outputs.repo_name }}-\K\d+\.\d+\.\d+[^\s]*" README.md)
          echo "version=$cap" >> "$GITHUB_OUTPUT"
      
      - name: Substitute version in README.md
        if: ${{ steps.readme.outputs.version != steps.tag.outputs.version }}
        id: sub_readme
        run: sed -i 's/${{ steps.repo.outputs.repo_name }}-${{ steps.readme.outputs.version }}/${{ steps.repo.outputs.repo_name }}-${{ steps.tag.outputs.version }}/g' README.md

      - name: Push with modified tag
        if: steps.sub_readme.conclusion == 'success'
        run: |
          git config author.name GitHub Actions
          git config author.email actions@github.com
          git add .
          git commit -m "Update version in README.md"
          git tag --annotate v${{ steps.tag.outputs.version }} -m "Version bump to v${{ steps.tag.outputs.version }}" --force
          git push
          git push --tags --force
        
  publish_release:
    runs-on: ubuntu-latest
    needs: version_check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: build/*.zip
