name: Update files with commit

on:
  push:
    tags:
      - v*.*.*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master

      - name: Check version in README.md
        id: file
        run: echo "name=version::$(grep -Eo git_practice-v[0-9]+\.[0-9]+\..+ README.md) | sed 's/^git_practice-//g'"

      - name: tag version
        id: tag
        run: echo "::name=version::$(git tag -l "v*"|tail -n1)"

      - name: Substitute
        id: sub
        if: ${{ steps.file.outputs.version }} != ${{ steps.tag.outputs.version }}
        run: sed -i 's/git_practice-${{ steps.file.outputs.version }}/git_practice-${{ steps.tag.outputs.version }}/g' README.md

      - name: Remove tag
        id: remove_tag
        if: steps.sub.conclusion == 'success'
        run: |
          git tag -d ${{ steps.tag.outputs.version }}
          # git push origin --delete ${{ steps.tag.outputs.version }}

      - name: Push changes
        if: steps.remove_tag.conclusion == 'success'
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: .
          tag: ${{ steps.tag.outputs.version }}
          message: "Update version in file."

  # publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         token: ${{ secrets.GITHUB_TOKEN }} # You need to create your own token with commit rights
  #         ref: master # The branch you want to commit to

  #     - name: Push changes
  #       uses: EndBug/add-and-commit@v9
  #       with:
  #         committer_name: GitHub Actions
  #         committer_email: actions@github.com
  #         add: .
  #         message: "update files"
