name: CD/version bump
run-name: |
  Version bump - Version bump - ${{ github.event.inputs.bump_type }}
  ${{ startsWith(github.event.inputs.bump_type, 'pre') && github.event.inputs.preid || '' }}

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: "Version bump types"
        required: true
        type: choice
        default: "patch"
        options:
          - major
          - premajor
          - minor
          - preminor
          - patch
          - prepatch
          - prerelease
      preid:
        description: "Prerelease identifier"
        type: string

jobs:
  version_check:
    name: Update Readme and Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CHANGELOG.md
          sparse-checkout-cone-mode: false

      - name: Bump changelog version
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: bump
          version: ${{ github.event.inputs.bump_type }}
          preid: ${{ github.event.inputs.preid }}
          keep-unreleased-section: true
          fail-on-empty-release-notes: true

      - name: Get version
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: latest

      - name: Save cache to Changelog.md
        uses: actions/cache/save@v4
        with:
          path: CHANGELOG.md
          key: version-bump-v${{ steps.query-release-info.outputs.version }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: release
          client-payload: >-
            {
              "bump_type": "${{ github.event.inputs.bump_type }}",
              "version": "${{ steps.query-release-info.outputs.version }}"
            }
